[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
selene = "Kampfkarren/selene@0.25.0"
rojo = "quenty/rojo@7.4.1-quenty-npm-canary.3"
lune = "filiptibell/lune@0.8.0"
