gitSourceBranch = "main"

[[classOrder]]
classes = ["RailUtil"]

[[classOrder]]
classes = ["--------"]

[[classOrder]]
section = "FusionUtil"
classes = ["FusionUtil", "[0.2.0] FusionUtil", "[0.2.5] FusionUtil", "[0.3.0] FusionUtil"]