std = "roblox+testez"

[rules]
shadowing = "allow"
multiple_statements = "allow"
unused_variable = "allow"
empty_if = "allow"
if_same_then_else = "allow"
parenthese_conditions = "allow"
undefined_variable = "allow"
manual_table_clone = "allow"
global_usage = "allow"
mixed_table = "allow"