[package]
name = "raildex/railutil"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.16.0"
Signal = "lucasmzreal/fastsignal@10.2.1"