[package]
name = "raild3x/railutil"
description = "A collection of utility functions for Roblox Luau."
authors = ["Logan Hunt (Raildex)"]
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4.0.0"
Janitor = "howmanysmall/janitor@^1.16.0"
Signal = "lucasmzreal/fastsignal@^10.2.1"
Fusion = "elttob/fusion@0.2.0"