[package]
name = "raild3x/railutil"
description = "A collection of utility functions for Roblox Luau."
authors = ["Logan Hunt (Raildex)"]
version = "1.6.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4.0.0"
Janitor = "howmanysmall/janitor@^1.16.0"
Signal = "lucasmzreal/fastsignal@^10.2.1"
Fusion_v0_2_0 = "elttob/fusion@0.2.0"
#Fusion_v0_2_5 = "raild3x/fusion@0.2.5"
Fusion_v0_3_0 = "elttob/fusion@0.3.0"