[package]
name = "raild3x/railutil"
description = "A collection of utilities functions for Roblox Luau."
authors = ["Logan Hunt (Raildex)"]
version = "1.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "default.project.json", "LICENSE"]

[dependencies]
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@1.16.0"
Signal = "lucasmzreal/fastsignal@10.2.1"
fusion = "elttob/fusion@0.2.0"